# pandas

pandas is a library for working with tables of data. It is especially useful when your data has named columns.

In [1]:
import pandas as pd

## DataFrames

The main pandas object is the `DataFrame`, which looks a lot like a spreadsheet.

In [3]:
df = pd.DataFrame({
    "name": ["Ada", "Grace", "Linus", "Guido"],
    "score": [9, 8, 7, 10],
    "passed": [True, True, False, True],
})
df

    name  score  passed
0    Ada      9    True
1  Grace      8    True
2  Linus      7   False
3  Guido     10    True

Columns can be selected by name.

In [4]:
df["score"]

0     9
1     8
2     7
3    10
Name: score, dtype: int64

## Adding a new column

You can create a new column from old ones.

In [5]:
df["score_times_two"] = 2 * df["score"]
df

    name  score  passed  score_times_two
0    Ada      9    True               18
1  Grace      8    True               16
2  Linus      7   False               14
3  Guido     10    True               20

## Filtering rows

A comparison gives a boolean series, and that can be used to filter the table.

In [6]:
df["score"] >= 9

0     True
1    False
2    False
3     True
Name: score, dtype: bool

In [ ]:
df[df["score"] >= 9]

## Useful summaries

pandas makes it easy to compute quick summaries.

In [ ]:
df["score"].mean()

In [ ]:
df.describe()

**Exercise**

Create a new column called `bonus` which is equal to `score + 1`.

Then show only the rows where `bonus` is at least `10`.

In [ ]:
# Write your answer here

::: {note} Solution (Don't look until you're done)
:class: dropdown

One possible answer is:

```python
df["bonus"] = df["score"] + 1
df[df["bonus"] >= 10]
```
:::